### ISSUE TITLE
Update for Foundry 11

### ISSUE THREAD

**Issue by Rubengam3r** [frondeus/fvtt-syrin-control#100]
**Is your feature request related to a problem? Please describe.**
Foundry is now version 11 build 301

**Describe the solution you'd like**
Core version is no longer supported for the module. And wanted to know if this is going to be updated to support foundry 11

**Describe alternatives you've considered**

**Additional context**

**Comment by frondeus** [comment]
#101 will bring the support for it.

**Comment by frondeus** [comment]
Released in https://github.com/frondeus/fvtt-syrin-control/releases/tag/0.5.0
