### ISSUE TITLE
Syntax Error 

### ISSUE THREAD

**Issue by Rubengam3r** [frondeus/fvtt-syrin-control#109]
**Describe the bug**
I have macros set up that run through game.syrinscape.playElement(id) and when I execute the marcro I get no sound.

**Screenshots**
![Screenshot 2023-07-21 113435](https://github.com/frondeus/fvtt-syrin-control/assets/32652791/dcc9de1d-ac31-4fe7-b090-11b8ed9034a2)
![Screenshot 2023-07-21 113508](https://github.com/frondeus/fvtt-syrin-control/assets/32652791/0da6d7d3-526b-4faa-982f-85c0c6e37ba2)

**Details**

<!-- please complete the following information:
 - OS: Windows 11
 - Browser: Opera GX
 - Foundry VTT version 11 build 306
 - Module version: 0.5.1

**Comment by egonil** [comment]
This looks to be the same thing as #98

**Comment by frondeus** [comment]
It isn't.

Looking into the screenshot I can see that after `// Explosion` there is `}`.
That `}` should be in the next line.
Otherwise Javascript tells you that it is a syntax error because you have unmatched brackets.

Now, I'm curious if this `}` was generated by my module or not.

@Rubengam3r could you show me the screenshot of the macro itself? Did you add your own code to the macro? Are you using monk active tiles for the macro?

**Comment by Rubengam3r** [comment]
Sure I can get that to you. But I am not using MAT at all for them. They are a macro that I am using for weapon and spell sounds that get activated. All that is in the macro is game.syrinscape.playElement(id); the id is the element id

**Comment by frondeus** [comment]
What I meant is, I'm trying to understand if this `}` that is supported to be in the next line, is generated by my module or not.

At first glance I don't see anything related to it that would be suspicious but perhaps it is connected to different OS? Are you using by any chance Windows?

**Comment by Rubengam3r** [comment]
Yes I am using Windows 11

**Comment by frondeus** [comment]
Okay, I suspect line endings.
Just to be sure, I changed the comment style from inline `//` to block `/* */`.
The inline comment takes the whole line, so if you type `}` afterward, it is ignored by the browser.

Contrary to it, a block comment has an explicit ending, so everything you type after the browser recognizes it.

Hopefully, that will help.

Let's see. PR: #110

**Comment by frondeus** [comment]
I released https://github.com/frondeus/fvtt-syrin-control/releases/tag/0.5.2
Before I publish it on foundry-vtt, I would love to hear the feedback if that helps.

To install this pre-release module, please install it manually by setting manifest link to https://github.com/frondeus/fvtt-syrin-control/releases/download/0.5.2/module.json

**Comment by Rubengam3r** [comment]
I will load it up and see.

**Comment by Rubengam3r** [comment]
I found that if I change the //Explosion to a block quote /*Explosion*/ it works out without any issue.

**Comment by frondeus** [comment]
Since that's exactly what release changed, I'm marking it as closed :)
