### ISSUE TITLE
Support FoundryVTT v12

### ISSUE THREAD

**Issue by chrispickford** [frondeus/fvtt-syrin-control#118]
**Is your feature request related to a problem? Please describe.**
FoundryVTT has now released stable v12 (Build 324) but this module only supports v11.

**Describe the solution you'd like**
Please update this module to support v12.

**Additional context**
FoundryVTT v12 release notes: https://foundryvtt.com/releases/12.324

**Comment by chillman0122** [comment]
FWIW I'm not getting any sound out of Syrin control after the v12 update.

**Comment by Morfedel** [comment]
neither have I; I know new updates break things, but still, a little frustrtating. Anyone know if they are paying attention to this?

**Comment by roi007leaf** [comment]
Doesn't look like there has been an update for a while, just use Kenkufm and discord

**Comment by frondeus** [comment]
Sorry, I decided to stop maintaining this project. I updated the README.

**Comment by alessiocali** [comment]
If it's of any help, I believe updating `getAudioContext` to `getAnalyzerContext` in `game.ts` should suffice to support V12. At least that's what I see from a quick and dirty experiment. I would issue a pull request but I don't have a suitable environment set up yet, I'd need to spend some time getting that running (and educate myself in some concepts I'm not familiar with)

**Comment by scooper4711** [comment]
Someone should suggest this plugin to https://github.com/League-of-Foundry-Developers to see if someone else wants to maintain it.

**Comment by chillman0122** [comment]
> Someone should suggest this plugin to https://github.com/League-of-Foundry-Developers to see if someone else wants to maintain it.

Done, comment is here https://github.com/orgs/League-of-Foundry-Developers/discussions/7#discussion-6863684

**Comment by alessiocali** [comment]
Proposed a possible fix in #119
