### ISSUE TITLE
cant upload CSV File

### ISSUE THREAD

**Issue by KurseDarkstone** [frondeus/fvtt-syrin-control#22]
so your tutorial was amazing... though kinda stuck in one spot. I have the CSV file from Syrinscape. but not seeing how to actually upload the file. not sure if its a compatibility issue with the new version or not. 
![image](https://user-images.githubusercontent.com/64416670/145072021-e5965ebd-3bc7-4ad4-864f-386eac48d35b.png)

**Comment by daggerfortysix** [comment]
I ran into this issue as well and wanted to share what I did to get around it. (Please note that I host my Foundry on The Forge.) After downloading my Syrinscape Remote Control Link csv, I changed .csv to .jpg, uploaded that file into my Assets on the Forge, and then changed .jpg back to .csv. After that I was able to link to the file via the Control Links in the SyrinControl settings and everything works perfectly. I figured I would share this workaround until an appropriate fix is done. Thank you!

**Comment by frondeus** [comment]
Okay, thanks! I will look into it as soon as I can

**Comment by frondeus** [comment]
Hi, first of all, thanks for making this issue @KurseDarkstone, and thanks, @daggerfortysix, for finding the workaround.
Unfortunately, I'm not using the CSV file method, so I missed that issue.

I confirm, you cannot upload the CSV file using the Foundry file picker. The Foundry does not support JSON/CSV format, so I need to figure out another way. For now, the workaround found by @daggerfortysix seems to be the only solution.

If you are running Foundry locally, it should be possible just to put CSV in the correct directory and select it (only the upload part should not be working) with the file picker. If that's not working as well, I'd instead consider making a separate issue ("I cant select CSV using the filepicker").
