### ISSUE TITLE
Import from CSV not working

### ISSUE THREAD

**Issue by JamzTheMan** [frondeus/fvtt-syrin-control#26]
I just tried importing my CSV and I got info messages saying it worked but I don't seem to have any moods or elements?

I can use the macro function to play sounds so everything else seems to be working ok.  Am I missing something?  I'm self hosting on my remote linux VM and my csv is 20mb with 44k entries (in case I'm hitting a data limit?)

![image](https://user-images.githubusercontent.com/8051654/147701881-0084863a-a6f6-41b0-986b-7c1c131a5815.png)

![image](https://user-images.githubusercontent.com/8051654/147701892-7b84d9e1-3f6c-44a8-8cf6-9c5a4bed541c.png)

![image](https://user-images.githubusercontent.com/8051654/147701855-da5feac8-5841-4247-84d5-9152d3bd615a.png)

**Comment by frondeus** [comment]
Hi @JamzTheMan -  that was an excellent catch.
I guess I need some automatic tests to detect such an issue in the future.

Sorry, I released 0.2.1 with a bug fix - it should be available in the next couple of minutes.

**Comment by JamzTheMan** [comment]
Awesome,, that did the trick!
