### ISSUE TITLE
Can not hear sounds

### ISSUE THREAD

**Issue by coumbsek** [frondeus/fvtt-syrin-control#28]
Hi, I think I have correctly followed the CSV tutorial, I see all my soundsets and moods in the drop-downs but when I play them I can not hear anything and even the browser does not display the sound logo nor windows seeing it in the sound manager.

What can I do and what additionnal informations can I provide you ?

**Comment by frondeus** [comment]
Hello,
SyrinControl does not provide audio, and I do not intend to add this feature. You need to use Syrinscape Online Player to hear the sound.
https://syrinscape.com/online/ 

See step 2.

Now after you installed and linked your Syrinscape Online account with the player, do you hear sounds? If not does the "currently playing" mood in Syrinscape Online Player changes when you change the active scene in Foundry?

**Comment by coumbsek** [comment]
Ok yeah it works perfectly I just did not understood that it was "solely" an automatic/programmable remote controler for online syrinscape. Now that I know that I should be able to used it to it's full potential.

Thanks again
