### ISSUE TITLE
I have tried the CSV way and it isn't working for me. Not clever enough for the API version

### ISSUE THREAD

**Issue by YenBenGrey** [frondeus/fvtt-syrin-control#29]
Hello there, 

I followed the steps for the CSV version and I get the drop down menu in Foundry but once I choose something, the box greys out and I can't choose anything to play.

I have my Foundry hosted remotely by Molten, that is the only thing I can think of that might be a problem. 

Please help. I have been a sub to Syrin for well over a year and love it. Just this week gone from roll20 to Foundry and it has changed everything. Just need decent sounds now. Don't want to use the Syrinscape control separately. Thank you for any help. 

I have attached before choosing and after choosing screenshots. 
<img width="413" alt="Screenshot 2022-01-20 at 12 15 29" src="https://user-images.githubusercontent.com/98095856/150337020-b5227613-ff63-4fde-89c3-1ec479145773.png">
<img width="315" alt="Screenshot 2022-01-20 at 12 15 39" src="https://user-images.githubusercontent.com/98095856/150337045-e0b7466d-4829-4b17-a45b-ac2331ae616c.png">

**Comment by TheJoiningGame** [comment]
Same thing happens for me.

**Comment by frondeus** [comment]
Hi, first of all sorry that you had to wait so long. I don't know why I missed your message.
Are there any errors that you can see? Both in the notification and in the console?

Also I'd need some more information to fully investigate whats going on.

Could you please send me extra details:

 - OS: [e.g. Windows 10, Ubuntu 20.10, macOS Catalina]
 - Browser [e.g. chrome 56, safari 12, firefox 90] (Also could you check if this happens only in one browser?)
 - Foundry VTT version [e.g. 8.2, v9]
 - Module version: [e.g. 0.1.0, 0.2.0, 0.2.1]
 - Does it work in Safety Mode (without other plugins enabled)

Also I'd need probably some logs to exactly know what went wrong, to do so please follow these instructions:

To retrieve logs:
* Chrome: Chrome settings button -> More tools -> Developer tools -> Console tab.
* Firefox: Hamburger button (right top corner) -> More Tools -> Web Developer Tools -> Console tab.
* Internet Explorer: press F12 -> Console on the right.
* Microsoft Edge: Click three dots (upper-right corner) -> More tools -> Developer tools -> Console tab.
* Safari: Safari menu -> Preferences -> Advanced tab -> Show Develop -> Develop menu -> Show Web Inspector -> Console tab.

Reload Foundry, then reproduce steps.
Click & drag to select all text,
Right click > Copy
Paste it into surrounding fences (Three backticks), like this:
````
```
SyrinControl | Loading...
SyrinControl | Loaded
```
````

**Comment by YenBenGrey** [comment]
Hello there,

I appreciate you getting back to me. I’d forgotten all about this. 

I’m sorry but I’ve since cancelled Syrinscape and I’m now using Tabletop Audio through Foundry. 

I’ve sent an e mail to Syrinscape to let them know how great they are and will happily go back if they can integrate with Foundry. 

I want everything to run through Foundry and not have anything running externally. 

Thank you for getting back to me. 

Rev. Garry Miller
Ordained Dudeist Priest at Dudeism, the Church of the Latter-Day Dude

**Comment by frondeus** [comment]
Alright, in that case, I'm closing this issue for now. If you change your mind and find that the bug still exists, don't hesitate to reopen it.
