### ISSUE TITLE
API playMood is not a function

### ISSUE THREAD

**Issue by Puddinglord** [frondeus/fvtt-syrin-control#36]
**Describe the bug**
I looked in the API and found a `playMood` function but calling it in Foundry doesn't work. The console says it's not a function and looking at the object in the console it's correct.

**To Reproduce**
1. Create a macro with the contents `game.syrinscape.playMood(817702);`
2. Look in the console and see this error

**Expected behavior**
Expecting to be able to call this function to play moods in addition to elements.

**Screenshots**
<img width="517" alt="image" src="https://user-images.githubusercontent.com/4474799/164031392-f6a744a8-5d1f-4133-8ee7-eef8d196d44c.png">

**Details**
 - OS: MacOS Monterey
 - Browser Chrome 98.17.1.18689
 - Foundry VTT version v9
 - Module version: 3.0.0
 - [ ] Does it work in Safety Mode (without other plugins enabled): No, still an issue.
 - [x] I did read FAQ - https://github.com/frondeus/fvtt-syrin-control/wiki/Frequently-Asked-Questions

Additional Info:
Here is the function I'm talking about: https://github.com/frondeus/fvtt-syrin-control/blob/master/src/syrin/services/api.ts#L94

**Comment by frondeus** [comment]
I just released new version of SyrinControl which adds `playMood` as well as the UI interface to generate macro.

https://github.com/frondeus/fvtt-syrin-control/releases/tag/0.4.0-alpha-1
