### ISSUE TITLE
Using the macros to play Moods doesn't work

### ISSUE THREAD

**Issue by mikejtarg** [frondeus/fvtt-syrin-control#37]
Using the macro function to play moods for example 

game.syrinscape.playElement(68039);

doesn't work. I get the 403 error in the console see attached image
![Screenshot_1](https://user-images.githubusercontent.com/63415533/169920011-022b7597-f1dd-4187-93d7-f34abe1d07ff.png)

Please advise

**Comment by mikejtarg** [comment]
Also, the following macro does function as expected even though the macro stops all other sounds in the Audio playlist tab
![image](https://user-images.githubusercontent.com/63415533/169920540-dcc96f46-7676-4c94-8262-15da041cb16c.png)

**Comment by TR7Mike** [comment]
I'm pretty sure it should be playMood and not playElement. There is a bug open for it, but it looks like the playMood function was removed according to one of the commits: https://github.com/frondeus/fvtt-syrin-control/commit/1c02d9da20e6b33b842f3a78c126f54913c73e72

**Comment by frondeus** [comment]
First of all sorry for late response. 
It seems that this and #36 are the one and the same. 

Indeed currently the feature of playing moods via macro has been removed.
Unfortunately, now I cannot invest my personal time in this project, and honestly, I'm thinking about finding a new maintainer.

**Comment by frondeus** [comment]
Well, good news, things changed, and I just released the first pre-release version that allows you to play moods from a macro!

https://github.com/frondeus/fvtt-syrin-control/releases/tag/0.4.0-alpha-1

**Comment by frondeus** [comment]
I am going to close it in favor of #36
