### ISSUE TITLE
Does not play in browser?

### ISSUE THREAD

**Issue by G3LL0** [frondeus/fvtt-syrin-control#39]
Is this addon only supposed to control the proprietary syrinscape online player, or is the sound scape supposed to actually play through foundry?

If that's the case, how ccan my players hear my souncscapes?

**Comment by karpana** [comment]
It's only purpose is to make the necessary webcalls to control the syrinacape online player

**Comment by karpana** [comment]
Depending how you chat with your players (eg via discord) there are ways to pipe it from the player right into your audio tool(s) of choice.
