### ISSUE TITLE
making automatic sounds that trigger when certain skills are used. 

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [frondeus/fvtt-syrin-control#41]
**Is your feature request related to a problem? Please describe.**
the issue i have is that id like to have a way for sounds to auto playback when certain skills and spells are cast. i used to have a mod in fantasy grounds that would look up chat messages and play the according sound via syrnscape. 

i.e if it saw damage and the word fireball it would play the fireball explosion linked with syrnscape. i was wondering if this mod would cover that. 

i know that automatic animations has a possibility to work in conjunction with this mod so they btoh play the animation and the sound but as im not a programmer i wouldnt know how to start and where to make the progress. so i would ask you if you know how to get this going?

**Describe the solution you'd like**
the solution id like is to contribute to a project that would encoperate sounds selected from the syrinscape library to auto play based on what system is being used and what spells/skills/class abilities/ if it rolls a crit or fail. and to set the sounds from the library.

**Comment by YenBenGrey** [comment]
I use midi qol macro fields. I set up a Syrinscape sound in a macro. Then instruct the item to fetch that macro when the item does something. Like I have short sword swoosh macro run after the attack. Then another slash macro run after damage.

**Comment by frondeus** [comment]
Hi, I guess Automatic Animations could work, indeed.
I am not expert in that module tho.
It seems that you can use macros with automatic animations: https://github.com/otigon/automated-jb2a-animations/wiki/Adding-Macros

You can create a macro for syrinscape element (for example swoosh macro) by following this tutorial:
https://github.com/frondeus/fvtt-syrin-control/wiki/How-To-Use#how-to-access-global-one-shot-elements

Then, you should be able to follow tutorial for Adding Macros in automated animations to play the element.

**Comment by frondeus** [comment]
I am closing the issue, I think both YenBenGrey and I answered the question
