### ISSUE TITLE
Extend the api to support fetching soundsets, onlineGlobalElements and onlineElements

### ISSUE THREAD

**Issue by tposney** [frondeus/fvtt-syrin-control#46]
**Is your feature request related to a problem? Please describe.**
Was looking at using this module to enhance the sounds players can play in midi-qol. To do this effectively I'd need to be able to show a list of one shots that they can use. I'm not aware of anyway to do that at present. Extending the pulblished api would make this  straight forward for me.

**Describe the solution you'd like**
Add the following in initSettings game.setGlobal
```js
        soundSources: async() => {
           return api.onlineSoundsets()
        },
        onlineElements: async(id) => {
            return api.onlineElements(id)
        },
        onlineGlobalElements: async () => {
            return api.onlineGlobalElements();
        }
```

**Describe alternatives you've considered**
Other than reinventing the wheel I can't see a good alternative.

**Additional context**
I hacked my local copy of syrinControl and the suggested changes seem to give me what I would need.

Thanks for your consideration. And a really nice piece of work by the way.

**Comment by YenBenGrey** [comment]
Hi Frondeus,
It was me who poked TPosney (the genius behind midi qol). I think it would be great to integrate. Being able to add one shots to critical hits or critical fails. As usual I’m available for testing.
