### ISSUE TITLE
[FVTT V10] New Scene will make this module play "empty" mood set.

### ISSUE THREAD

**Issue by sanpats** [frondeus/fvtt-syrin-control#49]
**Describe the bug**

Activate a newly saved or created scene under Foundry V10 will make SyrinControl playing "" (empty) soundset/moodset which does nothing, not even stop the currently playing moodset. It's just annoying.

**To Reproduce**

1. Upgrade to Foundry VTT V10.288.
2. Create a new scene and activate it.

**Expected behavior**

When setting no soundset/no moodset in the scene's ambient setting, no audio should start when activate the scene.

**Screenshots**

![image](https://user-images.githubusercontent.com/22677493/196056590-10894873-d839-4266-bb67-1abbecd7afc5.png)
![image](https://user-images.githubusercontent.com/22677493/196056600-a45b3053-183f-440e-a7fd-92f06410a630.png)

**Details**

- OS: Windows 11
 - Browser chrome 56
 - Foundry VTT version v10.288
 - Module version: 0.3.1
 - [No ] Does it work in Safety Mode (without other plugins enabled)
 - [Yes ] I did read FAQ - https://github.com/frondeus/fvtt-syrin-control/wiki/Frequently-Asked-Questions

**Logs**

```
raw.ts:58          GET https://syrinscape.com/online/frontend-api/moods//play/?auth_token=XXX 404
playMood @ raw.ts:58
playMood @ api.ts:109
setMood @ syrin.ts:33
setActiveMood @ syrin.ts:53
(anonymous) @ main.ts:99
#call @ foundry.js:724
callAll @ foundry.js:681
callback @ foundry.js:12767
(anonymous) @ foundry.js:12715
_handleUpdateDocuments @ foundry.js:12715
_updateDocuments @ foundry.js:12592
await in _updateDocuments (async)
update @ commons.js:6771
await in update (async)
updateDocuments @ commons.js:6128
update @ commons.js:6225
activate @ foundry.js:20784
callback @ foundry.js:68453
#onClickItem @ foundry.js:55711
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
raw.ts:58          GET https://syrinscape.com/online/frontend-api/moods//play/?auth_token=XXX 404
playMood @ raw.ts:58
playMood @ api.ts:109
setMood @ syrin.ts:33
setActiveMood @ syrin.ts:53
(anonymous) @ main.ts:99
#call @ foundry.js:724
callAll @ foundry.js:681
callback @ foundry.js:12767
(anonymous) @ foundry.js:12715
_handleUpdateDocuments @ foundry.js:12715
_updateDocuments @ foundry.js:12592
await in _updateDocuments (async)
update @ commons.js:6771
await in update (async)
updateDocuments @ commons.js:6128
update @ commons.js:6225
unsetFlag @ commons.js:6406
initialize @ token-attacher.js:188
(anonymous) @ token-attacher.js:218
#call @ foundry.js:724
call @ foundry.js:706
draw @ foundry.js:23596
await in draw (async)
view @ foundry.js:20815
_onActivate @ foundry.js:21033
_onUpdate @ foundry.js:20956
callback @ foundry.js:12766
(anonymous) @ foundry.js:12715
_handleUpdateDocuments @ foundry.js:12715
_updateDocuments @ foundry.js:12592
await in _updateDocuments (async)
update @ commons.js:6771
await in update (async)
updateDocuments @ commons.js:6128
update @ commons.js:6225
activate @ foundry.js:20784
callback @ foundry.js:68453
#onClickItem @ foundry.js:55711
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
2foundry.js:58721 SyrinControl | Playing "" from ""
foundry.js:3092 Foundry VTT | Synchronized official game time in 106ms
```

**Additional context**

In Logs posted above, I edited my auth token out.

**Comment by sanpats** [comment]
I think this issue is obsolete in the v0.4.0. My apologies.

**Comment by frondeus** [comment]
Hi, thanks for submitting this issue. I admit I didn't port the 0.3.x version of the plugin to the V10 and unfortunately I have no manpower to do so.

**Comment by frondeus** [comment]
I'm closing this issue for now since all my power is targeted towards releasing 0.4 with V10 support.
