### ISSUE TITLE
Add option to disable notifications

### ISSUE THREAD

**Issue by eXaminator** [frondeus/fvtt-syrin-control#53]
I would like to be able to disable the notifications that are shown everythime a command was sent to syrinscape. There are multiple ways I could see this change.

1. Just add an option to allow people to simply deactivate the notifications.
2. Replace it by better UX/UI solutions. Maybe show a small loading indicator on the button the user clicked until the command was successful. Or display that loading indicator somewhere else unobstrusive but visible. Maybe some small syrinscape icon in the top right corner of the canvas that animates in some way until the command was successful.

**Comment by frondeus** [comment]
Fixed in 0.4.0-beta2
