### ISSUE TITLE
v10 module.json using depreciated objects - warnings at startup

### ISSUE THREAD

**Issue by Truncated** [frondeus/fvtt-syrin-control#54]
**Describe the bug**
Depreciation warnings show on load.

**To Reproduce**
Install module
Load Foundry to setup screen. Compatibility warning shows: 
![image](https://user-images.githubusercontent.com/14208325/204111646-7eeaf37e-a515-4126-99f0-0e5c978c99f5.png)
Check console.
![image](https://user-images.githubusercontent.com/14208325/204111648-37ab0087-c695-4c4d-8950-9b1a4d53cd59.png)

**Expected behavior**

No warnings

**Screenshots**

See above

**Details**
 - OS: Windows 10
 - Browser: chrome
 - Foundry VTT version: v10.290
 - Module version:  0.4.0-alpha-4
 - [N/A ] Does it work in Safety Mode (without other plugins enabled)
 - [X] I did read FAQ - https://github.com/frondeus/fvtt-syrin-control/wiki/Frequently-Asked-Questions
-->

**Logs**

See above

**Additional context**

**Comment by frondeus** [comment]
Fixed in 0.4.0-beta2
