### ISSUE TITLE
Sounds not playing when a player triggers the macro (especially in Item macro)

### ISSUE THREAD

**Issue by YenBenGrey** [frondeus/fvtt-syrin-control#62]
**Describe the bug**

When I create a macro and then put it in Item Macro so that it will play when anyone triggers it, it only triggers or plays when the DM triggers it. 
A)If I get the link directly from Syrnscape and put it in the item macro like this fetch("link"); then it works no matter who triggers it. 
B) If I put it in the item macro like this example game.syrinscape.playElement(415635) then it will only trigger if the DM activates the spell or feature. 
C) Equally if I write game.syrinscape.playElement("link') it doesn't work for anyone. 

**To Reproduce**

<!-- Steps to reproduce the behavior:
1. Go to item
2. Open item macro
3. Paste in the macro script
4. Trigger the item
5. A) Works no errors
B) Doesn't work no errors
C) Doesn't work with errors see screenshots

**Expected behavior**

The item is activated and the sound plays no matter who triggers it. 

**Screenshots**

**Details**

<!-- please complete the following information:
 - OS: Mac OS Ventura 13.2
 - Browser: Chrome when prepping and Kenku FM when playing
 - Foundry VTT version 10.291

 - Module version: 0.4.0

<img width="292" alt="Syrincontrol" src="https://user-images.githubusercontent.com/98095856/213881910-5fc2cd3d-d3c8-45bb-9e59-8a2c8b8dbd92.png">
<img width="1507" alt="Toll_the_Dead_Frondeus_example" src="https://user-images.githubusercontent.com/98095856/213881952-482cef45-4a72-4798-81ee-1b88ecf7bb07.png">
![Errors](https://user-images.githubusercontent.com/98095856/213882000-83550e46-4fbb-4657-bbcd-54280f19f4bb.png)

**Comment by frondeus** [comment]
Sorry for the late response!

A) Yeah, that works because it's not related to SyrinControl.

B) that should work and I don't know why it does not. Could you send me logs if there are any errors when the player tries that? Because I couldn't reproduce it on my site.

C) That is invalid syntax, SyrinControl does not support link arguments, only element IDs.
