### ISSUE TITLE
"Each player needs to open Syrinscape Online Player and link to your Syrinscape account"

### ISSUE THREAD

**Issue by arcanjl** [frondeus/fvtt-syrin-control#67]
Is this still true? 
It says in the faq "This is no longer true with the beta 0.4.0. Audio will play in Foundry."

But my players cannot hear anything I play.

**Comment by frondeus** [comment]
Hi, this is no longer true for 0.4.0. 

If your players do not hear audio, it is probably a bug.

One note - audio would play only after Foundry acquires audio context, and that happens after user moves mouse.

Anyway, please include the logs so I can figure out why it's not working.

**Comment by arcanjl** [comment]
Do they have to have Syrinscape open?
I do as the dm, cause when I closed it, the sounds stopped. Does that sound correct?

**Comment by frondeus** [comment]
In the 0.3.x version - yes.
In the 0.4.x version (which is not fully released yet but is recommended) - no. Both you and your players do not need Syrinscape open.

What version (exactly) of SyrinControl do you use?

**Comment by arcanjl** [comment]
3.1! (embarrassing) I just downloaded it, so I thought it was the new one.
Where can I get 4? I am looking for it...

**Comment by frondeus** [comment]
Okay, don't worry :) It has not been released via official foundry channel since I'm still polishing features, writing tests and ensuring best quality, but definitely is usable.

https://github.com/frondeus/fvtt-syrin-control/releases/tag/0.4.0-beta1

Here is a link with quick note how to install it.

**Comment by arcanjl** [comment]
Thank you!

**Comment by arcanjl** [comment]
This looks so amazing. I actually renewed my sub with syrinscape. They should be happy ;-)

Sent from my iPhone

On Feb 7, 2023, at 1:53 PM, Wojciech Polak ***@***.***> wrote:

﻿

Okay, don't worry :) It has not been released via official foundry channel since I'm still polishing features, writing tests and ensuring best quality, but definitely is usable.

https://github.com/frondeus/fvtt-syrin-control/releases/tag/0.4.0-beta1

Here is a link with quick note how to install it.

**Comment by frondeus** [comment]
Cool! Can I close the issue then?

**Comment by arcanjl** [comment]
Thank for your help :)
