### ISSUE TITLE
Monks active tiles

### ISSUE THREAD

**Issue by arcanjl** [frondeus/fvtt-syrin-control#69]
Trying to get a tile to play music. Works for all the sounds I have locally, but not a syrinscape. 
![image](https://user-images.githubusercontent.com/29612539/217609629-bbdcba9b-2241-4c53-9606-02fea922a374.png)

**Comment by Majea** [comment]
Support for Monk's Active Tiles would be amazing!

**Comment by arcanjl** [comment]
I thought it would, if it was local...

**Comment by Majea** [comment]
Actually, I have tried using a macro. It works for elements but not for moods. The `game.syrinscape` object exposes `playElement` but not `playMood`.
If what you want is to play an element, the macro will do the job. 
1. Create a macro 
```game.syrinscape.playElement(args[0]);```
2. Save it with a nice name such as `Synrinscape play element`
3. in your active tile, add an action `Execute macro` and select your new macro
4. In the arguments, put the id of the element you want to play.
5. save. 
Normally, that should work.

**Comment by arcanjl** [comment]
That’s great. Thank you. I am in your boat, but if I do a trap or something I know how now ☺️👍🏼

**Comment by frondeus** [comment]
> Actually, I have tried using a macro. It works for elements but not for moods. The game.syrinscape object exposes playElement but not playMood.

This is no longer true. It has been added in 0.4.0-alpha1

Anyway, I haven't tested interop with Monks Tiles yet, so I need to check it before I let you know what went wrong.

**Comment by arcanjl** [comment]
That is awesome! Can I buy you a coffee?

**Comment by YenBenGrey** [comment]
Hello there, 

What I would do, now that I have tested different things, is import a mood in to a playlist then in a Monk's tile, add, Play Playlist item on a click of the mouse. Or any other trigger for that matter.

**Comment by frondeus** [comment]
Instead of "Play sound file" please use "Play Playlist":
![image](https://user-images.githubusercontent.com/1165825/230609519-7f085f79-c278-40ee-aa65-636e5b0759f3.png)

That action works as intended. I will not implement support for "Play sound file" because syrinscape mood is not a single `wav` track - it is a set of multiple sounds played independently.
