### ISSUE TITLE
Changing Volume of syrinscape

### ISSUE THREAD

**Issue by superseva** [frondeus/fvtt-syrin-control#70]
**Describe the bug**

Changing volume of syrinscape slider in Foundry makes it goes really loud and distorted. 

**To Reproduce**
1. play some mood in foundry
2. change syrinscape volume in global controls in Foundry (turn down volume)
3. get your ears blasted :)

**Expected behavior**

turning the volume  down should make it more quiet 

**Details**
 - OS: Windows 10, 
 - Browser: chrome 110.0.5481.78
 - Foundry VTT version e.g. v10.291
 - Module version: 0.4.0 beta2
 - [] Does it work in Safety Mode (without other plugins enabled). The same issue
 - [x] I did read FAQ - https://github.com/frondeus/fvtt-syrin-control/wiki/Frequently-Asked-Questions

**Logs**

**Comment by frondeus** [comment]
Please update plugin to latest https://github.com/frondeus/fvtt-syrin-control/releases/download/0.4.0-beta5/module.json

Duplicate of #66

**Comment by superseva** [comment]
It works now as intended.
Although I am not sure if it is syrinscape normalization or something but the stream is a bit lower in volume then for example the local sounds. This goes only for the sounds regulated by the syrinscale slider. The Global/OneShots sounds seems to be loud as normal.
I am testing it on some official content from the syrinscape.

**Comment by superseva** [comment]
Oh, wait, Global is also changing the global volume, ah ok., never mind that was the thing. I thought global was for global effects.
Sorry for that

**Comment by frondeus** [comment]
Yes, those sliders act the same way how the sliders in the original Syrinscape client were working :)

**Comment by frondeus** [comment]
Is it solved? @superseva

**Comment by superseva** [comment]
Solved
