### ISSUE TITLE
Volume Control

### ISSUE THREAD

**Issue by frondeus** [frondeus/fvtt-syrin-control#8]
It would be cool to configure volume of Syrinscape just like we can control Foundry Volume

**Comment by JamzTheMan** [comment]
I'm really loving the SyrinControl now that cors has been fixed! The ability to easily create macros and throw them in Journals is great!

Any chance volume control will be coming anytime soon? Some "one shots" are just too low volume wise (has always been an issue with some soundsets/oneshots) so to add in a boost or change volume would be a welcome addition.

**Comment by frondeus** [comment]
Now, with this pre-release it's possible :)
https://github.com/frondeus/fvtt-syrin-control/releases/tag/0.4.0-alpha-2-2
