### ISSUE TITLE
Module Prevents Saving Changes in the Grid Configuration Tool

### ISSUE THREAD

**Issue by Urumii** [frondeus/fvtt-syrin-control#85]
When clicking "save changes" within the Grid Configuration Tool, nothing happens. It is only after disabling this module that I can make changes.

**Comment by frondeus** [comment]
Hi! I have few questions:
What version of the foundry are you using?
What version of SyrinControl?
Are there any logs (errors) in the console when it happens?

**Comment by Urumii** [comment]
What version of the foundry are you using?
Version 10 Build 291

What version of SyrinControl?
0.4.0-beta5

Are there any logs (errors) in the console when it happens?
No

--
Kim DeRider
Owner | Head Instructor

Fight or Flight Academy
7355 Washington Ave S
Edina, MN 55439

952-405-6110 |  <http://www.fightorflightacademy.com/>
http://www.fightorflightacademy.com

**Comment by frondeus** [comment]
Alright, I will try to reproduce it.
Meanwhile, could you upgrade the module to 0.4.0 stable release and see if the problem still occurs?

**Comment by Urumii** [comment]
I still have the issue with that version.

--
Kim DeRider
Owner | Head Instructor

Fight or Flight Academy
7355 Washington Ave S
Edina, MN 55439

952-405-6110 |  <http://www.fightorflightacademy.com/>
http://www.fightorflightacademy.com

**Comment by frondeus** [comment]
Did you, by any chance, link the scene to the mood (playlist sound) or perhaps create an ambient sound that is stored in the scene?

I think I managed to reproduce it, and I'm getting:

![image](https://user-images.githubusercontent.com/1165825/230601873-6e15b692-adf0-43f9-a151-16539b4dcd31.png)

Do you have a similar error in the console?
