### ISSUE TITLE
Syrinscape volume control under Global Volume Controls is not set correctly on new install.

### ISSUE THREAD

**Issue by voodoofrog** [frondeus/fvtt-syrin-control#86]
On a new install the control starts at the halfway point when it is actually full volume and to actually put it to half volume you have to set it to it full and then _back_ to half.

**To Reproduce**

1. Set up a fresh instance of Syrincontrol with no adjustments made.
2. Adjust the volume control to 100%.
3. Adjust the volume control to 50%.

The volume control should reflect the actual volume of the playing mood.

I would expect the volume to start at 100% or for it to get louder when adjusted to 100% in step 2.

**Details**

 - OS: Windows 11
 - Browser: Chrome 111
 - Foundry VTT version: v10.291
 - Module version: 0.4.0
 - [*] Does it work in Safety Mode (without other plugins enabled)
 - [*] I did read FAQ - https://github.com/frondeus/fvtt-syrin-control/wiki/Frequently-Asked-Questions
-->

**Additional context**

I have also had instances where after changing mood, the volume of the playing mood seems to have ignored my global volume setting and gone back to being louder than expected, although I cannot reproduce this in fresh world with no other modules, so I'm not entirely sure what happened.

**Comment by frondeus** [comment]
Hmm, yeah there is definitely something wrong, its probably aftermath after #58 .

**Comment by frondeus** [comment]
Okay, yeah. In the store initialization, I still had a default value of 50 (because the foundry volume is stored in the range of 0-100).
Meanwhile, syrinscape uses the range 0.0-1.0 :)

Fixed it in https://github.com/frondeus/fvtt-syrin-control/commit/1a0d6cdc2ee67aa1cf255a27037c6e180c0a8cb6
