### ISSUE TITLE
Incompatibility with Monks Sound Enhancements

### ISSUE THREAD

**Issue by frondeus** [frondeus/fvtt-syrin-control#95]
That fixed it, thanks!

I have one request, if possible.  It looks like the new UI improvement isn't compatible with the module Monk's Sound Enhancements.  It's not completely broken.  It's very minor, actually.  That module adds tabs to the Edit Playlist box, and that pushes the rest of the content down, but the box doesn't resize to account for this.  It also adds some additional options that go away when Syrincontrol is present.  Here are some screenshots to demonstrate.

Only Syrincontrol: 
![image](https://user-images.githubusercontent.com/28198633/230674217-25e650d4-aedc-4ea6-92ed-607ecc2d3ccf.png)

Only Monk's Sound Enhancements:
![image](https://user-images.githubusercontent.com/28198633/230674329-5b02228e-4901-4be1-bd58-1dee416e2fe3.png)

Both modules:
![image](https://user-images.githubusercontent.com/28198633/230674355-676b4ad1-7df7-4f29-8719-58ab50f9ca29.png)

"No" is an acceptable answer for this one, but hopefully it's also an easy adjustment.  :)

_Originally posted by @notrealdan in https://github.com/frondeus/fvtt-syrin-control/issues/92#issuecomment-1500616691_

**Comment by frondeus** [comment]
Sooo the solution would be to somehow hide what monks module added?

I can try to do so but perhaps it should be added in that module instead?

Every playlist, ambient sound etc have aen extra flag `flags.syrinscape` so my module can detect that it is something that needs it's control.

So minks module could detect it too and abort adding the tab.

**Comment by notrealdan** [comment]
Yes, I think having Monk's module ignore SyrinControl playlists would make the most sense.  I opened an issue for this on their github here:
https://github.com/ironmonk88/monks-sound-enhancements/issues/14

**Comment by notrealdan** [comment]
This was fixed in the latest version of Monk's module.  This issue can be closed!
